server:
  port: 8080

spring:
  boot:
    admin:
      client:
        url: http://localhost:1080
        instance:
          metadata:
            user.name: admin
            user.password: admin
  hcc:
    cache:
      enabled: true
      metrics:
        enabled: true
      local:
        initialCapacity: 1000
      hotspot:
        readHotKeyThreshold: 80.1
      circuitBreaker:
        failureThreshold: 10
  redis:
    redisson:
      file: classpath:redisson-config.yml
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 2000ms

management:
  server:
    address: 127.0.0.1
    port: 8080
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  security:
    enabled: false
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      # 采集抽样，1.0代表所有的链路都会被跟踪
      probability: 1.0